export default [
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "FHB",
    consignmentNumber: "24563278",
    origin: "Jaipur",
    destination: "Patna",
    createdBy: "ASK Reatils",
    dateCreated: "2019-04-15",
  },
  {
    consignmentName: "ATY",
    consignmentNumber: "98765463",
    origin: "Pune",
    destination: "Surat",
    createdBy: "DJD Reatils",
    dateCreated: "2020-06-15",
  },
  {
    consignmentName: "ATU",
    consignmentNumber: "34526176",
    origin: "Bangalore",
    destination: "Delhi",
    createdBy: "ADJ Reatils",
    dateCreated: "2020-03-15",
  },
  {
    consignmentName: "DSA",
    consignmentNumber: "98734576",
    origin: "Shimla",
    destination: "Kolkata",
    createdBy: "KFJ Reatils",
    dateCreated: "2020-06-10",
  },
  {
    consignmentName: "ERT",
    consignmentNumber: "24352435",
    origin: "Goa",
    destination: "Kerala",
    createdBy: "RET Reatils",
    dateCreated: "2020-01-10",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
  {
    consignmentName: "ASD",
    consignmentNumber: "23456434",
    origin: "Bangalore",
    destination: "Kolkata",
    createdBy: "ABC Reatils",
    dateCreated: "2016-08-01",
  },
];
